# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install self
    before: |
      ./bashbox build --release
      ./bashbox selfinstall
      source $HOME/.bashbox/env # This is not necessary for new terminals

  - name: Show help
    command: bashbox --help

workspaceLocation: bashbox/bashbox.code-workspace
additionalRepositories:
  - url: https://github.com/bashbox/std
  - url: https://github.com/bashbox/argbash

vscode:
  extensions:
    - timonwong.shellcheck
    - mads-hartmann.bash-ide-vscode
    - evgeniypeshkov.syntax-highlighter
