image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "Compile self" # runs during prebuild
    init: "bash bashbox build --release"
