# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install self
    before: |
      ./bashbox build --release
      ./bashbox selfinstall
      source $HOME/.bashbox/env # This is not necessary for new terminals

vscode:
  extensions:
    - timonwong.shellcheck
    - mads-hartmann.bash-ide-vscode
    - evgeniypeshkov.syntax-highlighter
